### ISSUE TITLE
FrSky FRSIM not working

### ISSUE THREAD

**Issue by pljeroen** [skyfpv/FlowState#11]
FrSky FRSIM dongle: 83042057000000000000504944564944,FrSky Simulator,platform:Windows,leftshoulder:b0,rightshoulder:b3,leftx:a2,lefty:a3,rightx:a1,righty:a0,lefttrigger:a4,righttrigger:a5,

No movement on any switch/stick.

https://imgur.com/a/NHRUk6I

**Comment by skyfpv** [comment]
Thanks for the info! Try dropping this file in "FlowState\2.79\datafiles\gamecontroller" (replace the existing gamecontrollerdb.txt)
[gamecontrollerdb.txt](https://github.com/skyfpv/FlowState/files/3756343/gamecontrollerdb.txt)

**Comment by skyfpv** [comment]
Let us know if that works for ya @pljeroen and we'll make it part of the next release. Also, if you wanted to give us the string for the Jumper T16, that would be help out our other jumper users quite a bit

**Comment by pljeroen** [comment]
Sadly doesnt work. Need to get Jumper T16 working on windows level first. I will give that a go in a bit and open a new issue for the T16 to keep things a bit organized ;)

**Comment by skyfpv** [comment]
This has been fixed
