### ISSUE TITLE
Controller settings - switches dont seem to work

### ISSUE THREAD

**Issue by pljeroen** [skyfpv/FlowState#17]
In the controller settings, it shows the switch channel values, but the switches dont move accordingly. On the screenshot, both switches are in 3rd pos, as is evidenced by the values, but this doesnt show in the graphical representation of the switch.

They DO actually work in the game.

![no_switch_movement_2020-02-07 11_06_06-](https://user-images.githubusercontent.com/47155642/74020526-0a034880-499a-11ea-91d4-d2df3e025f3c.png)

**Comment by skyfpv** [comment]
Good catch. I'll see if I can get that fixed up

**Comment by skyfpv** [comment]
This has been pushed the the latest release
