### ISSUE TITLE
Sound cause lag

### ISSUE THREAD

**Issue by error414** [skyfpv/FlowState#2]
After start simulator first sound on the track (if you fly through green wall) cause short grafic lag. Simulator freezes for a while. Next sounds are ok, I think it can cause load sound from disk to memory. 

Win10 V1803 / I5-3320M / HD4000 / 16GB / SSD 500GB / Frsky X7 connected as HID

**Comment by skyfpv** [comment]
This issue has been fixed in the newest release. If you could verify that it's better on your end @error414 , that would be great!
