### ISSUE TITLE
Spektrum Radio controller mapping

### ISSUE THREAD

**Issue by djslack** [skyfpv/FlowState#22]
Hello,

I have a Spektrum DXe with the Spektrum USB receiver. My mapping string is:
`83042b57000000000000504944564944,SPEKTRUM RECEIVER,platform:Windows,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,`

Once I found the second gamecontrollerdb.txt file I was able to get this to work, mostly. I can't get reset and arm to show in the controller setup UI (numbers change in the array though) and couldn't get antimicro to register any of the two position switches, but this seems like a start.

**Comment by skyfpv** [comment]
Yup. So the switches are likely working, but they don't show up in the UI. This is a known bug and should be fixed soon. I'll make sure to get this dongle added for the next release!

**Comment by skyfpv** [comment]
This has been pushed the the latest release
