### ISSUE TITLE
Controller mapping.

### ISSUE THREAD

**Issue by Bthanse** [skyfpv/FlowState#24]
![bilde](https://user-images.githubusercontent.com/61755834/75809008-4c952680-5d88-11ea-8364-c4576ed278a5.png)

**Comment by skyfpv** [comment]
We should be able to get this controller added, but first can I get some extra details about it? What type of controller is it, and do you think you could also include at least two triggers in the mapping so that users can arm and reset?

**Comment by Bthanse** [comment]
It is Esky 0905A. It have only two sticks, no switches.
.

Vennlig hilsenBjørn Terje Hansebråten 

    På onsdag 4. mars 2020, 23:56:35 CET skrev Sky FPV <notifications@github.com> følgende:  
 
 
We should be able to get this controller added, but first can I get some extra details about it? What type of controller is it, and do you think you could also include at least two triggers in the mapping so that users can arm and reset?

**Comment by skyfpv** [comment]
Ok thanks for the info. We'll get this added in the next release!
