### ISSUE TITLE
Channel inversion doesn't save on steam version

### ISSUE THREAD

**Issue by pljeroen** [skyfpv/FlowState#25]
In the settings, controller section, inverting and applying any channel, does not save. Going back into the controller section shows all channels uninverted after changing them to inverted and applying.

**Comment by skyfpv** [comment]
We caught this one just after you and others reported it. We pushed a fix this morning. If your game doesn't update automatically try uninstalling and reinstalling. There's a minor UX bug that was introduced as a result, but the functionality now works. Thanks for reporting this!
