### ISSUE TITLE
Controller Settings

### ISSUE THREAD

**Issue by DavidPaget** [skyfpv/FlowState#26]
Hi, could you please add FlySky Nirvana N14
Controller mapping string:
4e281057000000000000504944564944,FlySky NV14 Joystick,platform:Windows,a:a6,b:a7,y:a5,start:a4,leftx:a3,lefty:a2,rightx:a0,righty:a1,lefttrigger:b1,righttrigger:b2,

**Comment by skyfpv** [comment]
This has been pushed the the latest release
