### ISSUE TITLE
Green wall problem, not counted

### ISSUE THREAD

**Issue by error414** [skyfpv/FlowState#4]
I tried to create my own track and I have problem with counting, if I fly through green wall in gates. I think (hope) that gates have good number. It happend quite often, approx two times per one track. Each flight it happen in another gate. 

See video. https://youtu.be/pO3B4h3VQMI  
[custom.zip](https://github.com/skyfpv/FlowState/files/2655240/custom.zip)

Win10 V1803 / I5-3320M / HD4000 / 16GB / SSD 500GB / Frsky X7 connected as HID

**Comment by skyfpv** [comment]
This is an issue I was afraid of seeing. The cpu isn't running the physics loop fast enough. This means the quad is essentially teleporting from point A, to point B without colliding with any of the space in between once it reaches a high enough speed. The solution to this is to get a faster computer (not a good solution), or implement a fix on the game engine side. I already have a feature request for a solution posted here https://github.com/UPBGE/blender/issues/951
