### ISSUE TITLE
Controller

### ISSUE THREAD

**Issue by sfjuocekr** [skyfpv/FlowState#6]
Could you maybe add an entry for my USB controller in gamecontrollerdb.txt?

https://github.com/sfjuocekr/SBUS-joystick

It shows up in Windows as "Serial/Keyboard/Mouse/Joystick", this is the default channel map:

PITCH = channel 1 = Y
ROLL = channel 2 = X
THROTTLE = channel 3 = Z
YAW = channel 4 = Z rotate
AUX1 = channel 5 = X rotate
AUX2 = channel 6 = Y rotate
SWA = channel 7 (3-point) = button 1/2/3
SWB = channel 8 (3-point) = button 4/5/6 
SWC = channel 9 (2-point)  = button 7/8
SWD = channel 10 (2-point)  = button 9/10

**Comment by sfjuocekr** [comment]
03000000c01600008704000000000000,Serial/Keyboard/Mouse/Joystick,leftx:a5,lefty:a2,rightx:a0,righty:a1,lefttrigger:a3,righttrigger:a4,platform:Windows,

That should be the line to add, I've added it in gamecontrollerdb.txt, but it won't work.

**Comment by sfjuocekr** [comment]
Nevermind, got it working!

I edited the wrong file hahaha.

**Comment by skyfpv** [comment]
@sfjuocekr Do you think you could share the line that ended up working for you? I would like to add it to the official release so that other people don't have this issue. Also, what controller or dongle were you using?

**Comment by sfjuocekr** [comment]
03000000c01600008804000000000000,Teensy Flight Sim Controls,leftx:a5,lefty:a2,rightx:a0,righty:a1,lefttrigger:a3,righttrigger:a4,platform:Windows,

and for the old one:

03000000c01600008704000000000000,Serial/Keyboard/Mouse/Joystick,leftx:a5,lefty:a2,rightx:a0,righty:a1,lefttrigger:a3,righttrigger:a4,platform:Windows,


Sorry for the very late response!
