### ISSUE TITLE
Adding controller

### ISSUE THREAD

**Issue by Thunder92Storm** [skyfpv/FlowState#70]
Hello, I'm new on this sim and would like to add my FlySky controller, I've already done the mapping here it is:
4e28ff7f000000000000504944564944,FS-i6S emulator,platform:Windows,leftshoulder:b0,rightshoulder:b5,leftx:a3,lefty:a2,rightx:a0,righty:a1,lefttrigger:a4,righttrigger:a5,
Have nice day

**Comment by Thunder92Storm** [comment]
I made a mistake because for the trigger I used the VrA and B of my controller and it doesn't work correctly on the computer so use that mapping instead:
4e28ff7f000000000000504944564944,FS-i6S emulator,platform:Windows,leftshoulder:b0,rightshoulder:b5,leftx:a3,lefty:a2,rightx:a0,righty:a1,lefttrigger:b1,righttrigger:b3,
Sorry

**Comment by skyfpv** [comment]
awesome. I'll get this added in the next release

**Comment by skyfpv** [comment]
This issue has been fixed in the latest steam release
